export const ALL_COURSES = [
  {
    tp: "澳門勞工事務局",
    name: "美髮師(初級)考證課程",
    start_date: "26 Jun 25",
    duration: "124.5小時",
    type: "Full Time",
    course_fee: "630.00",
    funding: "315.00",
    tags: ["美髮師(初級)"],
  },
  {
    tp: "澳門勞工事務局",
    name: "美容師(初級)考證課程",
    start_date: "27 Jun 25",
    duration: "124.5小時",
    type: "Full Time",
    course_fee: "630.00",
    funding: "315.00",
    tags: ["美容師(初級)"],
  },
  {
    tp: "澳門勞工事務局",
    name: "酒店業職場英語-中階課程",
    start_date: "23 Sep 25",
    duration: "30小時",
    type: "Full Time",
    course_fee: "Free",
    funding: "N/A",
    tags: ["酒店業職場英語(中級)"],
  },
  {
    tp: "澳門勞工事務局",
    name: "影視製作機燈從業員培訓課程",
    start_date: "23 Sep 25",
    duration: "30小時",
    type: "Full Time",
    course_fee: "Free",
    funding: "N/A",
    tags: ["影視製作（初級）"],
  },
  {
    tp: "澳門勞工事務局",
    name: "家用空調深度清洗課程",
    start_date: "23 Sep 25",
    duration: "30小時",
    type: "Full Time",
    course_fee: "Free",
    funding: "N/A",
  },
  {
    tp: "澳門勞工事務局",
    name: "溝通技巧與正向態度課程",
    start_date: "23 Sep 25",
    duration: "30小時",
    type: "Full Time",
    course_fee: "Free",
    funding: "N/A",
  },
  {
    tp: "澳門勞工事務局",
    name: "CSA(Certified SOC Analyst)安全運營中心分析師認證課程",
    start_date: "23 Sep 25",
    duration: "30小時",
    type: "Full Time",
    course_fee: "Free",
    funding: "N/A",
  },
];
